name: Docker Build Test

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --no-cache -t build-test .
